const mongoose=require("mongoose")
const userSchema=new mongoose.Schema({
    firstName:{
        type:String,
        required:true,
        trim:true
    },
    lastName:{
        type:String,
        required:true,
        trim:true
    },
    email:{
        type:String,
        required:true,
        trim:true,
        unique:true
        },
    phone:{
        type:Number,
        trim:true,
        required:true
    },
    password:{
            type:String,
            required:true,
            trim:true
        }
})
module.exports=mongoose.model("Register",userSchema)